/* 
  Sketch generated by the Arduino IoT Cloud Thing "Projeto IoT"
  https://create.arduino.cc/cloud/things/1e7673db-d774-45ec-a346-c92a397fd18f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float potenciometro_1;
  bool led_1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  pinMode(12, OUTPUT);
  pinMode(34, INPUT);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  leituraPotenciometro();
}

/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
  // Add your code here to act upon Led1 change
  if (led_1 == 1){
    digitalWrite(12, HIGH);
  } else {
    digitalWrite(12, LOW);
  }
}


void leituraPotenciometro()  {
  // Add your code here to act upon Led1 change
  potenciometro_1 = analogRead(34);
  delay(10);
}
