// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "5e4312a4-ef1c-499c-b841-89bc30a746d4";

const char SSID[] = "123";
const char PASS[] = "123456789";
const char DEVICE_KEY[] = "sTzHPelSyc1Z@KAX!ywEZXgQA";

// Variáveis criadas na Arduino IoT Cloud
float potenciometro_1;
bool led_1;

// Protótipos das funções
void onLed1Change();
void leituraPotenciometro();


void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  ArduinoCloud.addProperty(potenciometro_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_1, READWRITE, ON_CHANGE, onLed1Change);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);